version: "3.8"

services: 
  # php:
  #   command: php -S 0.0.0.0:9000 -t ./
  #   links:
  #     - mysql
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    command: php -S 0.0.0.0:9000 -t ./
    ports:
      - "9000:9000"
    links:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'marchinhas'
      MYSQL_USER: 'user_root'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
volumes:
  mysql:

